on:
  pull_request:
  push:
    branches:
      - auto
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        toolchain: [ "gcc", "clang"]
    steps:
      - name: Cancel Stale Workflows
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - name: Compute cache key
        # this step works around a limitation in actions/cache
        # that does not allow updating a cache
        # so what we do here instead is
        #  1. generate a new id that gets refreshed every hour
        #   the limit is to reduce the chance of hitting the
        #   global 5GB limit per repo
        #  2. use that id as part of the cache identifier
        #  3. fallback (restore-keys) to the most recent cache
        id: cache_extra_id
        run: |
          echo "::set-output name=id::$(( $(date +'%s') / 60 / 60 ))"
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            /home/runner/.ccache
          key: ${{ runner.os }}-${{ matrix.toolchain }}-cacheID-${{ steps.cache_extra_id.outputs.id }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.toolchain }}-cacheID-
      - uses: actions/checkout@v2
        with:
           fetch-depth: 200
           submodules: true
      - name: install core packages
        run: |
          sudo apt-get update
          sudo apt-get -y install --no-install-recommends apt-utils dialog git iproute2 procps lsb-release
      - name: add testing toolchain
        run: |
          sudo apt-get -y install software-properties-common
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
      - name: install tool chain
        run: |
          sudo apt-get -y install libstdc++6 clang-format-5.0 ccache
          if test "${{ matrix.toolchain }}" = "gcc" ; then
            sudo apt-get -y install cpp-6 gcc-6 g++-6 
          else
            sudo apt-get -y install clang-5.0 llvm-5.0
          fi
      - name: install dependencies
        run: sudo apt-get -y install postgresql git build-essential pkg-config autoconf automake libtool bison flex libpq-dev parallel libunwind-dev
      - name: Build
        run: |
          if test "${{ matrix.toolchain }}" = "gcc" ; then
            export CC='gcc'
            export CXX='g++'
          else
            export CC='clang'
            export CXX='clang++'
          fi
          echo Build with $CC and $CXX
          ./ci-build.sh --use-temp-db
